### PR TITLE
Adapted the jQuery code to vanilla JS

### PR DESCRIPTION
**Pull request by PandelisZ**
Vanilla js implementation of jQuery onload, with support for IE8.

Tested working on current example

Issue: #1

### CODE REVIEW

**Comment by PandelisZ** [comment]
Turns out this wouldn't actually work in IE8 since querySelectorAll is not supported

**Comment by d4nt** [comment]
According to [this](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll): querySelectorAll is fine for CSS2 selectors. And "div.tweetthis" is an entirely CSS1 selector. So I think it should be ok. So I'll go ahead and merge it.

**Comment by wgx** [comment]
@PandelisZ Should we update the readme.md to say we no longer need jquery?

**Comment by d4nt** [comment]
I’ve just done this.

**Pull request merged**
